[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/admin.html"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin-login"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin-logout"
  function = "admin-logout"