[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = false

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/admin.html"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin-logout"
  function = "admin-logout"