// products.js — generiert vom Admin-Panel
// 22.2.2026, 09:50:22

const PRODUCTS = [
  {
    "id": 1,
    "name": "BrickJ Fingerski Starter goo",
    "category": "ski",
    "status": "sold-out",
    "priceUSD": 15,
    "priceCHF": 13.5,
    "priceEUR": 14,
    "stock": 10,
    "image": "fingerski_starterkit/starterset_view_img.JPG",
    "link": "fingerski_starterset.html",
    "description": "Finger-Ski Starter Set, nur in der Schweiz erhältlich."
  },
  {
    "id": 2,
    "name": "BrickJ Fingerski V2 Blue",
    "category": "ski",
    "status": "sold-out",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 15,
    "image": "blueski/blueskiV3_side.JPG",
    "link": "FingerskiV2_blue.html",
    "description": "Fingerskis in blau."
  },
  {
    "id": 3,
    "name": "Kinkrail Blue",
    "category": "obstacle",
    "status": "sold-out",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 8,
    "image": "bluekink/kinkrail_sideback.JPG",
    "link": "kinkrail_blue.html",
    "description": "Kinkrail in blau, im Starter Set inklusive."
  },
  {
    "id": 4,
    "name": "BrickJ_MTB Sender BJFR",
    "category": "mtb",
    "status": "sold-out",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 0,
    "image": "sender/Sendersidewide.JPEG",
    "link": "Pink_bike_productpage.html",
    "description": "Downhill Fingerbike – Sender."
  },
  {
    "id": 5,
    "name": "BrickJ_MTB V10",
    "category": "mtb",
    "status": "sold-out",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 0,
    "image": "v10/V10sideback.JPEG",
    "link": "V10.html",
    "description": "Fingerbike V10 Style."
  },
  {
    "id": 6,
    "name": "Roll-In",
    "category": "obstacle",
    "status": "available",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 5,
    "image": "rollin/Rollinwhole.JPEG",
    "link": "mtb_rollin.html",
    "description": "Roll-In Obstacle."
  },
  {
    "id": 7,
    "name": "Hardline Step-Up Kicker",
    "category": "obstacle",
    "status": "available",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 5,
    "image": "mtbkicker/Kickersidetop.JPEG",
    "link": "mtb_kicker.html",
    "description": "Hardline Step-Up Kicker."
  },
  {
    "id": 8,
    "name": "BrickJ_MTB Session 9",
    "category": "mtb",
    "status": "soon",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 0,
    "image": "COMING SOON.png",
    "link": "soon.html",
    "description": "Bald verfügbar."
  },
  {
    "id": 9,
    "name": "BrickJ_MTB Trickshot",
    "category": "mtb",
    "status": "soon",
    "priceUSD": 2,
    "priceCHF": 1.8,
    "priceEUR": 1.9,
    "stock": 0,
    "image": "COMING SOON.png",
    "link": "soon.html",
    "description": "Dirtjump Fingerbike."
  },
  {
    "id": 10,
    "name": "BrickJ_MTB Starterkit",
    "category": "kit",
    "status": "soon",
    "priceUSD": 4,
    "priceCHF": 3.6,
    "priceEUR": 3.8,
    "stock": 0,
    "image": "COMING SOON.png",
    "link": "soon.html",
    "description": "Includes one Fingerbike and Hardline Kicker."
  },
  {
    "id": 11,
    "name": "BrickJ_MTB Advanced-Kit",
    "category": "kit",
    "status": "soon",
    "priceUSD": 5,
    "priceCHF": 4.5,
    "priceEUR": 4.7,
    "stock": 0,
    "image": "COMING SOON.png",
    "link": "soon.html",
    "description": "Includes one Fingerbike, Hardline Kicker and Roll-In."
  },
  {
    "id": 12,
    "name": "BrickJ_MTB Ultimate-Kit",
    "category": "kit",
    "status": "soon",
    "priceUSD": 9,
    "priceCHF": 8.1,
    "priceEUR": 8.5,
    "stock": 0,
    "image": "COMING SOON.png",
    "link": "soon.html",
    "description": "Includes all Fingerbikes, Hardline Kicker and Roll-In."
  }
];

const LEGACY_MAP = {
  'V10.html':                   'v10',
  'Pink_bike_productpage.html': 'sender',
  'FingerskiV2_blue.html':      'fingerski-v2-blue',
  'FingerkiV2_pink.html':       'fingerski-v2-pink',
  'FingerskiV2_black.html':     'fingerski-v2-pink',
  'kinkrail_blue.html':         'kinkrail-blue',
  'kinkrail_pink.html':         'kinkrail-pink',
  'kinkrail_black.html':        'kinkrail-black',
  'fingerski_starterset.html':  'fingerski-starter-set',
  'mtb_rollin.html':            'rollin',
  'mtb_kicker.html':            'hardline-kicker',
  'Session-9.html':             'session-9',
};
