// products.js
// ═══════════════════════════════════════════════════════
// ZENTRALE PRODUKTDATENBANK — hier alles bearbeiten!
// Oder über das Admin-Panel (admin.html) verwalten.
// ═══════════════════════════════════════════════════════

const PRODUCTS = [
  {
    id: 'fingerski-starter-set',
    name: 'BrickJ Fingerski Starter Set',
    category: 'ski',
    status: 'available',       // 'available' | 'sold-out' | 'soon'
    priceUSD: 15,
    priceCHF: 13.50,
    priceEUR: 14.00,
    stock: 10,
    etsyLink: 'https://www.ricardo.ch/de/a/fingerski-set-1310687260/',
    etsyLabel: 'Buy on ricardo.ch',
    description: 'Finger-Ski Starter Set — only available in Switzerland.',
    specs: [
      'Includes: 2x Fingerskis + 1x Kinkrail',
      'Color: Blue',
      'Material: PLA (3D-Printed)',
    ],
    note: 'Physical product — ships within Switzerland only.',
    images: [
      'fingerski_starterkit/starterset_view_img.JPG',
      'fingerski_starterkit/starterset_on_kicker.JPEG',
      'fingerski_starterkit/fingerski_trick.JPEG',
      'fingerski_starterkit/blue_shaper_in_use.JPEG',
    ],
  },
  {
    id: 'fingerski-v2-blue',
    name: 'BrickJ Fingerski V2 — Blue',
    category: 'ski',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 15,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Printable finger ski files in blue. Comes included with the Starter Set.',
    specs: [
      'Length: 9.5 cm',
      'Width: 2.8 cm',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'blueski/blueskiV3_side.JPG',
      'blueski/blueskiis_frontleft.JPG',
      'blueski/blueskiis_top.JPG',
      'blueski/blueskiV3_taken_appart.JPG',
    ],
  },
  {
    id: 'fingerski-v2-pink',
    name: 'BrickJ Fingerski V2 — Pink',
    category: 'ski',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 15,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Printable finger ski files in pink.',
    specs: [
      'Length: 9.5 cm',
      'Width: 2.8 cm',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'pinkski/pinkskiis_front.JPG',
      'pinkski/pinkskiis_frontleft.JPG',
      'pinkski/pinkskiis_front_far_away.JPG',
    ],
  },
  {
    id: 'kinkrail-blue',
    name: 'Kinkrail — Blue',
    category: 'obstacle',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 8,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Ski rail with kink — blue. Comes included with the Starter Set.',
    specs: [
      'Length: 17.8 cm',
      'Height: 4.9 – 7.3 cm',
      'Width: 5 cm',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'bluekink/kinkrail_sideback.JPG',
      'bluekink/kinkrail_blue_sideback.JPG',
      'bluekink/kinkrail_blue_sideback2.JPG',
      'bluekink/kinkrail_blue_sidetop.JPG',
    ],
  },
  {
    id: 'kinkrail-pink',
    name: 'Kinkrail — Pink',
    category: 'obstacle',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 8,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Ski rail with kink — pink.',
    specs: [
      'Length: 17.8 cm',
      'Height: 4.9 – 7.3 cm',
      'Width: 5 cm',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'pinkkink/kinkrail_pink_side.JPG',
      'pinkkink/kinkrail_pink_front.JPG',
      'pinkkink/kinkrail_pink_backside.JPG',
      'pinkkink/kinkrail_pink_wideback.JPG',
    ],
  },
  {
    id: 'kinkrail-black',
    name: 'Kinkrail — Black',
    category: 'obstacle',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 8,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Ski rail with kink — black.',
    specs: [
      'Length: 17.8 cm',
      'Height: 4.9 – 7.3 cm',
      'Width: 5 cm',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'blackkink/kinkrail_black_backside.JPG',
      'blackkink/kinkrail_black_front.JPG',
      'blackkink/kinkrail_black_side.JPG',
      'blackkink/kinkrail_black_sideback.JPG',
    ],
  },
  {
    id: 'sender',
    name: 'BrickJ_MTB Sender BJFR',
    category: 'mtb',
    status: 'sold-out',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Downhill Fingerbike — Sender style.',
    specs: [
      'Scale: 1:10 approx.',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'sender/Sendersidewide.JPEG',
      'sender/Senderside.JPEG',
      'sender/Senderfront.JPEG',
      'sender/Senderback.JPEG',
      'sender/Sendertop.JPEG',
    ],
  },
  {
    id: 'v10',
    name: 'BrickJ_MTB V10',
    category: 'mtb',
    status: 'sold-out',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Fingerbike — V10 downhill style.',
    specs: [
      'Scale: 1:10 approx.',
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'v10/V10side1.JPEG',
      'v10/V10sideback.JPEG',
      'v10/V10front.JPEG',
    ],
  },
  {
    id: 'rollin',
    name: 'Roll-In',
    category: 'obstacle',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 5,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Roll-In ramp obstacle for your finger MTB setup.',
    specs: [
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'rollin/Rollinwhole.JPEG',
      'rollin/Rollinside.JPEG',
      'rollin/Rollinsidewide.JPEG',
      'rollin/Rollinramp.JPEG',
    ],
  },
  {
    id: 'hardline-kicker',
    name: 'Hardline Step-Up Kicker',
    category: 'obstacle',
    status: 'available',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 5,
    etsyLink: '',
    etsyLabel: 'Buy STL Files on Etsy',
    description: 'Hardline Step-Up Kicker — perfect for big tricks.',
    specs: [
      'Files: STL + 3MF included',
    ],
    note: 'This product contains 3MF and STL files only — no physical product.',
    images: [
      'mtbkicker/Kickersidetop.JPEG',
      'mtbkicker/Kickerback.JPEG',
      'mtbkicker/Kickerwhole.JPEG',
    ],
  },
  {
    id: 'session-9',
    name: 'BrickJ_MTB Session 9',
    category: 'mtb',
    status: 'soon',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Coming Soon',
    description: 'Coming soon.',
    specs: [],
    note: '',
    images: ['COMING SOON.png'],
  },
  {
    id: 'trickshot',
    name: 'BrickJ_MTB Trickshot',
    category: 'mtb',
    status: 'soon',
    priceUSD: 2,
    priceCHF: 1.80,
    priceEUR: 1.90,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Coming Soon',
    description: 'Dirtjump Fingerbike — coming soon.',
    specs: [],
    note: '',
    images: ['COMING SOON.png'],
  },
  {
    id: 'starterkit-mtb',
    name: 'BrickJ_MTB Starterkit',
    category: 'kit',
    status: 'soon',
    priceUSD: 4,
    priceCHF: 3.60,
    priceEUR: 3.80,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Coming Soon',
    description: 'Includes one Fingerbike and Hardline Kicker.',
    specs: [],
    note: '',
    images: ['COMING SOON.png'],
  },
  {
    id: 'advanced-kit',
    name: 'BrickJ_MTB Advanced-Kit',
    category: 'kit',
    status: 'soon',
    priceUSD: 5,
    priceCHF: 4.50,
    priceEUR: 4.70,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Coming Soon',
    description: 'Includes one Fingerbike, Hardline Kicker and Roll-In.',
    specs: [],
    note: '',
    images: ['COMING SOON.png'],
  },
  {
    id: 'ultimate-kit',
    name: 'BrickJ_MTB Ultimate-Kit',
    category: 'kit',
    status: 'soon',
    priceUSD: 9,
    priceCHF: 8.10,
    priceEUR: 8.50,
    stock: 0,
    etsyLink: '',
    etsyLabel: 'Coming Soon',
    description: 'Includes all Fingerbikes, Hardline Kicker and Roll-In.',
    specs: [],
    note: '',
    images: ['COMING SOON.png'],
  },
];

// Alte HTML-Dateinamen → neue Produkt-IDs
// So funktionieren alte Links noch!
const LEGACY_MAP = {
  'V10.html':                'v10',
  'Pink_bike_productpage.html': 'sender',
  'FingerskiV2_blue.html':   'fingerski-v2-blue',
  'FingerkiV2_pink.html':    'fingerski-v2-pink',
  'FingerskiV2_black.html':  'fingerski-v2-pink', // kein black mehr → pink als fallback
  'kinkrail_blue.html':      'kinkrail-blue',
  'kinkrail_pink.html':      'kinkrail-pink',
  'kinkrail_black.html':     'kinkrail-black',
  'fingerski_starterset.html': 'fingerski-starter-set',
  'mtb_rollin.html':         'rollin',
  'mtb_kicker.html':         'hardline-kicker',
  'Session-9.html':          'session-9',
};

const FEATURED_IDS = ['fingerski-starter-set','sender','v10','fingerski-v2-blue','kinkrail-blue'];

// ═══════════════════════════════════════════════════════
// SITE CONFIG — alle Website-Texte & Einstellungen
// Wird vom Admin-Panel verwaltet
// ═══════════════════════════════════════════════════════
const SITE_CONFIG = {
  hero: {
    title: 'Ride Small.\nDream Big.',
    subtitle: 'Finger bikes & skis, built for tricks and fun — all year round.',
    buttonText: 'Shop Now',
    buttonLink: 'shop.html',
    badge: 'Handmade in Switzerland 🇨🇭',
  },
  popup: {
    enabled: true,
    page: 'index',         // 'index' | 'all' | 'shop' | 'product'
    delay: 2000,           // ms bis Popup erscheint
    title: 'Special Offer',
    subtitle: 'Fingerski Starter Set Pro',
    body: 'Now available exclusively in Switzerland.',
    image: 'uploads/fingerski-set_view_img.jpg',
    buttonText: 'Buy now on ricardo.ch',
    buttonLink: 'https://www.ricardo.ch/de/a/fingerski-set-1312438968/',
    dismissText: 'Close',
  },
  footer: {
    line1: 'BrickJ_mtb · Handmade in Switzerland 🇨🇭',
    line2: 'No cookies 🍪',
    privacyText: 'Privacy Policy',
  },
  shop: {
    heroTitle: 'Shop',
    heroEyebrow: 'The Collection',
    heroSub: 'Handcrafted 3D-printed miniatures for the culture',
  },
  trust: {
    badge: 'Handmade in Switzerland 🇨🇭',
    shipping: 'Ships within Switzerland',
  },
};